---
apiVersion: v1
kind: Service
metadata:
  name: plex-service
  namespace: plex
spec:
  selector:
    app: plex
  ports:
    - port: 32400 # Default Plex port, adjust if you're using a different one
      targetPort: 32400
  type: LoadBalancer # or NodePort
