---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-config
  namespace: plex
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC" # adjust accordingly
  VERSION: "docker"
  PLEX_CLAIM: "" # optional
